import fs from 'node:fs';
import Database from 'better-sqlite3';
import { serverConfig } from '../config';
import { getDb } from './messages_read';

/**
 * Single-operator chat UI state — survives page reloads + device switches.
 * The chat_user_state table has one row keyed 'operator'; we just store
 * which thread the operator was last viewing so that leaving the app and
 * coming back (or switching phone↔desktop) lands them in the right thread
 * instead of defaulting to 'default'.
 */
export function getActiveThread(): string {
	if (!fs.existsSync(serverConfig.memoryDbPath)) return 'default';
	const db = getDb();
	try {
		const row = db
			.prepare("SELECT last_thread FROM chat_user_state WHERE user_id = 'operator'")
			.get() as { last_thread?: string } | undefined;
		const cached = row?.last_thread;
		if (!cached || cached === 'default') return 'default';

		// Reconcile against reality. The cached last_thread can point at a
		// thread that no longer has messages OR was never persisted (operator
		// typed /new in a thread that errored out before its first message
		// landed). Audit 2026-05-27 caught a phantom "testing" thread that
		// pointed at nothing — page-reload landed on an empty fantasy thread.
		// Fall back to the most-recently-active real thread, or 'default'.
		const existsRow = db
			.prepare(
				`SELECT
					EXISTS(SELECT 1 FROM chat_messages WHERE thread_id = ?) AS in_msg,
					EXISTS(SELECT 1 FROM chat_thread_meta WHERE thread_id = ?) AS in_meta`
			)
			.get(cached, cached) as { in_msg: number; in_meta: number } | undefined;
		if (existsRow && (existsRow.in_msg || existsRow.in_meta)) return cached;

		const latest = db
			.prepare(
				`SELECT thread_id FROM chat_messages
				 GROUP BY thread_id
				 ORDER BY MAX(timestamp) DESC
				 LIMIT 1`
			)
			.get() as { thread_id?: string } | undefined;
		return latest?.thread_id || 'default';
	} catch (e: unknown) {
		console.error('getActiveThread error:', e);
		return 'default';
	} finally {
		db.close();
	}
}

export function setActiveThread(threadId: string): void {
	const t = (threadId || '').trim() || 'default';
	const db = new Database(serverConfig.memoryDbPath);
	try {
		db.prepare(
			`INSERT INTO chat_user_state (user_id, last_thread, updated_at)
			 VALUES ('operator', ?, CURRENT_TIMESTAMP)
			 ON CONFLICT(user_id) DO UPDATE SET last_thread = excluded.last_thread, updated_at = CURRENT_TIMESTAMP`
		).run(t);
	} catch (e: unknown) {
		console.error('setActiveThread error:', e);
	} finally {
		db.close();
	}
}

/**
 * RAW read of the persisted last-active thread — NO reconciliation. Unlike
 * getActiveThread() (which falls back to the latest real thread / 'default' for
 * the state endpoint), this returns exactly what's stored so the restore order
 * can apply its own existence gate. Returns null when nothing is persisted.
 */
export function getLastActiveThread(): string | null {
	if (!fs.existsSync(serverConfig.memoryDbPath)) return null;
	const db = getDb();
	try {
		const row = db
			.prepare("SELECT last_thread FROM chat_user_state WHERE user_id = 'operator'")
			.get() as { last_thread?: string } | undefined;
		const v = (row?.last_thread || '').trim();
		return v || null;
	} catch (e: unknown) {
		console.error('getLastActiveThread error:', e);
		return null;
	} finally {
		db.close();
	}
}

/**
 * A thread "exists" if it has at least one message OR a meta row. chat_messages
 * is guaranteed present post-bootstrap; chat_thread_meta self-creates lazily, so
 * its probe is guarded separately — a missing meta table must not mask a real
 * messages hit.
 */
export function threadExists(threadId: string): boolean {
	const t = (threadId || '').trim();
	if (!t) return false;
	if (!fs.existsSync(serverConfig.memoryDbPath)) return false;
	const db = getDb();
	try {
		const inMsg = db.prepare('SELECT 1 FROM chat_messages WHERE thread_id = ? LIMIT 1').get(t);
		if (inMsg) return true;
		try {
			const inMeta = db
				.prepare('SELECT 1 FROM chat_thread_meta WHERE thread_id = ? LIMIT 1')
				.get(t);
			if (inMeta) return true;
		} catch {
			/* chat_thread_meta not created yet — the messages probe above is authoritative */
		}
		return false;
	} catch (e: unknown) {
		console.error('threadExists error:', e);
		return false;
	} finally {
		db.close();
	}
}

/**
 * Resolve which thread a bare/​deep-linked chat open should land on, applying the
 * locked restore order EXACTLY:
 *
 *   1. URL param (`?thread=`) — only if it resolves to a real thread.
 *   2. else the persisted last-active thread (`chat_user_state.last_thread`)…
 *   3. …validated to still exist — a deleted thread falls through.
 *   4. else a fresh thread — ONLY as a last resort.
 *
 * `freshId` is generated by the caller (random/time-based) so this function stays
 * pure-over-the-DB and unit-testable. `deepLinkMiss` is true when a thread WAS
 * requested but could not be honored AND we landed on a real existing thread
 * instead (so the caller can show a plain-English "showing your latest chat"
 * fallback). It stays false when we fall through to a fresh thread — there's no
 * prior conversation to apologize for.
 */
export function resolveInitialThread(
	queryThread: string | null | undefined,
	freshId: string
): { thread: string; deepLinkMiss: boolean } {
	const q = (queryThread || '').trim();
	// 1. URL param, only if it resolves to a real thread.
	if (q && threadExists(q)) return { thread: q, deepLinkMiss: false };
	// 2 + 3. Persisted last-active, validated to still exist.
	const last = getLastActiveThread();
	if (last && threadExists(last)) {
		// q was set (a deep-link / explicit thread) but didn't resolve, and we have
		// a real thread to fall back to → signal the plain-English fallback.
		return { thread: last, deepLinkMiss: !!q };
	}
	// 4. Fresh thread — last resort. No prior conversation to point at.
	return { thread: freshId, deepLinkMiss: false };
}
